#if !defined(STYLE_DSL_ELEM_) && !defined(STYLE_DSL_ELEMSTATE_)
#error "This header should only be used as DSL"
#endif

#ifndef STYLE_DSL_ELEM_
#define STYLE_DSL_ELEM_(NAME, INDEX_NAME)
#endif

#ifndef STYLE_DSL_ELEMSTATE_
#define STYLE_DSL_ELEMSTATE_(NAME, INDEX_NAME)
#endif


STYLE_DSL_ELEM_(WND_HEADER                    , "WND_HEADER"     )
STYLE_DSL_ELEM_(WND_FRAME                     , "WND_FRAME"      )
STYLE_DSL_ELEM_(BUTTON                        , "BUTTON"         )
STYLE_DSL_ELEM_(CLOSE_BTN                     , "CLOSE_BTN"      )
STYLE_DSL_ELEM_(MINIMIZE_BTN                  , "MINIMIZE_BTN"   )
STYLE_DSL_ELEM_(SLIDER_THUMB                  , "SLIDER_THUMB"   )
STYLE_DSL_ELEM_(SLIDER_VTHUMB                 , "SLIDER_VTHUMB"  )
STYLE_DSL_ELEM_(SLIDER_HTHUMB                 , "SLIDER_HTHUMB"  )
STYLE_DSL_ELEM_(SLIDER_HBODY                  , "SLIDER_HBODY"   )
STYLE_DSL_ELEM_(SLIDER_VBODY                  , "SLIDER_VBODY"   )
STYLE_DSL_ELEM_(SLIDER_BODY_2D                , "SLIDER_BODY_2D" )
#if 0
STYLE_DSL_ELEM_(SCROLLBAR_ARROW_UP            , "SB_ARR_UP"      )
STYLE_DSL_ELEM_(SCROLLBAR_ARROW_DOWN          , "SB_ARR_DOWN"    )
STYLE_DSL_ELEM_(SCROLLBAR_ARROW_LEFT          , "SB_ARR_LEFT"    )
STYLE_DSL_ELEM_(SCROLLBAR_ARROW_RIGHT         , "SB_ARR_RIGHT"   )
STYLE_DSL_ELEM_(SCROLLBAR_THUMB_HORIZ         , "SB_HTHUMB"      )
STYLE_DSL_ELEM_(SCROLLBAR_THUMB_VERT          , "SB_HTHUMB"      )
STYLE_DSL_ELEM_(SCROLLBAR_THUMB_GRIPPER_HORIZ , "SB_HGRIP"       )
STYLE_DSL_ELEM_(SCROLLBAR_THUMB_GRIPPER_VERT  , "SB_HGRIP"       )
#endif


STYLE_DSL_ELEMSTATE_(NORMAL   , "NORMAL"   )
STYLE_DSL_ELEMSTATE_(HOVERED  , "HOVERED"  )
STYLE_DSL_ELEMSTATE_(PRESSED  , "PRESSED"  )
STYLE_DSL_ELEMSTATE_(INACTIVE , "INACTIVE" )


#undef STYLE_DSL_ELEM_
#undef STYLE_DSL_ELEMSTATE_
